# Generated by Django 3.1.1 on 2021-05-28 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=200, null=True)),
                ('ownername', models.CharField(blank=True, max_length=200, null=True)),
                ('device_name', models.CharField(blank=True, max_length=200, null=True)),
                ('total_kwh', models.FloatField(blank=True, max_length=200, null=True)),
                ('last_kwh', models.FloatField(blank=True, max_length=200, null=True)),
                ('new_kwh', models.FloatField(blank=True, max_length=200, null=True)),
                ('relay_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField(blank=True, max_length=200, null=True)),
                ('current', models.FloatField(blank=True, max_length=200, null=True)),
                ('total_kwh', models.FloatField(blank=True, max_length=200, null=True)),
                ('kwh_used', models.FloatField(blank=True, max_length=200, null=True)),
                ('time', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('relay_status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.device')),
            ],
        ),
    ]
